import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#f8f9fa',
        surface: '#f8f9fa',
        'surface-bright': '#f8f9fa',
        'surface-dim': '#d9dadb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'surface-container': '#edeeef',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'on-background': '#191c1d',
        'on-surface': '#191c1d',
        'on-surface-variant': '#58423d',
        'text-muted': '#5b5f60',
        'text-ai': '#191c1d',
        'forge-text': '#434748',
        'forge-label': '#58423d',
        outline: '#8b716b',
        'outline-variant': '#dfc0b9',
        'forge-border': '#dfc0b9',
        'border-subtle': '#e1e3e4',
        'input-bg': '#ffffff',
        primary: '#d95c41',
        'primary-container': '#d95c41',
        'on-primary': '#ffffff',
        'on-primary-container': '#ffffff',
        'forge-orange': '#D95C41',
        'panel-light': '#f8f9fa',
        error: '#ba1a1a',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        xs: '4px',
        base: '8px',
        sm: '12px',
        gutter: '16px',
        margin: '24px',
        md: '24px',
        lg: '48px',
        xl: '80px',
        'panel-padding': '20px',
        'margin-desktop': '64px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        display: ['Manrope', 'sans-serif'],
        headline: ['Manrope', 'sans-serif'],
        'headline-md': ['Manrope', 'sans-serif'],
        'headline-sm': ['Manrope', 'sans-serif'],
        'headline-lg': ['Manrope', 'sans-serif'],
        'label-caps': ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
        'label-sm': ['"JetBrains Mono"', 'monospace'],
        'code-sm': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['30px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'code-sm': ['13px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '700' }],
        'label-sm': ['11px', { lineHeight: '1', fontWeight: '500' }],
      },
    },
  },
} satisfies Config;
