import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'var(--assistant-background)',
        surface: 'var(--assistant-surface)',
        'surface-bright': 'var(--assistant-surface-bright)',
        'surface-dim': 'var(--assistant-surface-dim)',
        'surface-container-lowest': 'var(--assistant-surface-container-lowest)',
        'surface-container-low': 'var(--assistant-surface-container-low)',
        'surface-container': 'var(--assistant-surface-container)',
        'surface-container-high': 'var(--assistant-surface-container-high)',
        'surface-container-highest': 'var(--assistant-surface-container-highest)',
        'on-background': 'var(--assistant-on-background)',
        'on-surface': 'var(--assistant-on-surface)',
        'on-surface-variant': 'var(--assistant-on-surface-variant)',
        'text-muted': 'var(--assistant-text-muted)',
        'text-ai': 'var(--assistant-text-ai)',
        'forge-text': 'var(--assistant-forge-text)',
        'forge-label': 'var(--assistant-forge-label)',
        outline: 'var(--assistant-outline)',
        'outline-variant': 'var(--assistant-outline-variant)',
        'forge-border': 'var(--assistant-forge-border)',
        'border-subtle': 'var(--assistant-border-subtle)',
        'input-bg': 'var(--assistant-input-bg)',
        primary: 'var(--assistant-primary)',
        'primary-container': 'var(--assistant-primary-container)',
        'on-primary': 'var(--assistant-on-primary)',
        'on-primary-container': 'var(--assistant-on-primary-container)',
        'forge-orange': '#D95C41',
        'panel-light': 'var(--assistant-panel-light)',
        error: 'var(--assistant-error)',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        xs: '4px',
        base: '8px',
        sm: '12px',
        gutter: '16px',
        margin: '24px',
        md: '24px',
        lg: '48px',
        xl: '80px',
        'panel-padding': '20px',
        'margin-desktop': '64px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        display: ['Manrope', 'sans-serif'],
        headline: ['Manrope', 'sans-serif'],
        'headline-md': ['Manrope', 'sans-serif'],
        'headline-sm': ['Manrope', 'sans-serif'],
        'headline-lg': ['Manrope', 'sans-serif'],
        'label-caps': ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
        'label-sm': ['"JetBrains Mono"', 'monospace'],
        'code-sm': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['30px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'code-sm': ['13px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '700' }],
        'label-sm': ['11px', { lineHeight: '1', fontWeight: '500' }],
      },
    },
  },
} satisfies Config;
